### PR TITLE
Created unit test for AclEntryBuilder. Resolved #1251

### LINKED ISSUE #1251: Create unit test for AclEntryBuilder.
Do it similarly like for https://github.com/abixen/abixen-platform/blob/v-1-0-wave-2-refactor/abixen-platform-core/src/test/java/com/abixen/platform/core/domain/model/UserBuilderTest.groovy

### PR DESCRIPTION
**Pull request by vinodpandey1**
@mariuszkumor Please review the PR for the AclEntryBuilder unit tests .
As this is my first PR Would like to get your feedback if i am going wrong somewhere .

### CODE REVIEW

**Comment by mariuszkumor** [comment]
The commit created from wrong account. Check your .gitconfig. Email or username is not like as your GitHub account.

**Comment by vinodpandey1** [comment]
@mariuszkumor corrected it was from itoxygen.io which i was working with long back

**Comment by vinodpandey1** [comment]
@mariuszkumor should i do a new branch and commit it again ?

**Comment by mariuszkumor** [comment]
@vinodpandey1 - it's up to you how to do. The repo expect correct commit from github account :-)

**Comment by vinodpandey1** [comment]
Do i need to change the username also to vinodpandey1

**Pull request closed without merging**
