### PR TITLE
236-Migrate logger to log4j 2 for the web client microservice

### PR DESCRIPTION
**Pull request by nagukothapalli**
Please review the changes.
Added log4j2.xml and respective dependencies.
No changes in the java code. because it already  using slf4j classes.

### CODE REVIEW

**Comment by mariuszkumor** [comment]
Could you change please commit title to: 
Migrated logger to log4j 2 for the web client microservice. Resolved #236   ?

**Comment by mariuszkumor** [comment]
And one more thing, please add lombok similarly as here https://github.com/abixen/abixen-platform/commit/0c90402419ad775f6844c5c730b5074d6cf2a8e5 and inject logger by lombock annotation.

**Comment by nagukothapalli** [comment]
yep . sure

**Comment by mariuszkumor** [comment]
You have 2 commits now. Please make rebase and remove old one.

**Comment by nagukothapalli** [comment]
is it possible to make it  at your end?

**Comment by mariuszkumor** [comment]
Unfortunately not.

**Pull request closed without merging**
